const hi = 'HELLO'
const alphaL = 'abcdefghijklmnopqrstuvwxyz'
const alphaU = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
const alpha = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

//===================================
// https://www.codewars.com/kata/5a25ac6ac5e284cfbe000111
// If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a much harder version of this one.
// https://www.codewars.com/kata/insane-coloured-triangles

// A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

// The different possibilities are:

// Colour here:        G G        B G        R G        B R
// Becomes colour:      G          R          B          G
// With a bigger example:

// R R G B R G B B
//  R B R G B R B
//   G G B R G G
//    G R G B G
//     B B R R
//      B G R
//       R B
//        G
// You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given RRGBRGBB you should return G.

// The input string will only contain the uppercase letters R, G, B and there will be at least one letter so you do not have to test for invalid input.
// If you are only given one colour as the input, return that colour.
// Adapted from the 2017 British Informatics Olympiad

function triangle(row) {
    if(row.length < 2) return row

    const rgb = ["R", "G", "B"]

    let newRow = ""
    while(row.length > 1){
        for(let i=0 ; i<row.length-1 ; i++){
            let start = row[i]
            let end = row[i+1]
            if(start === end) newRow += start
            else newRow += rgb.find(el => el!==start && el!==end)
        }
        row = newRow
        newRow = ""
    }

    return row
}

// console.log(triangle("RRGBRGBB")) // "G"

function triangleBis(row){
    if(row.length < 2) return row

    const rgb = ["R", "G", "B"]

    let newRow = ""
    for(let i=0 ; i<row.length-1 ; i++){
        let start = row[i]
        let end = row[i+1]
        if(start === end) newRow += start
        else newRow += rgb.find(el => el!==start && el!==end)
    }
    return triangleBis(newRow)
}

// console.log(triangleBis("RRGBRGBB")) // "G"

//=========================================
// Task
// Given an array/list [] of n integers , find maximum triplet sum in the array Without duplications .

// Notes :
// Array/list size is at least 3 .

// Array/list numbers could be a mixture of positives , negatives and zeros .

// Repetition of numbers in the array/list could occur , So (duplications are not included when summing).

// Input >> Output Examples
// 1- maxTriSum ({3,2,6,8,2,3}) ==> return (17)
// Explanation:
// As the triplet that maximize the sum {6,8,3} in order , their sum is (17)

// Note : duplications are not included when summing , (i.e) the numbers added only once .

// 2- maxTriSum ({2,1,8,0,6,4,8,6,2,4}) ==> return (18)
// Explanation:
// As the triplet that maximize the sum {8, 6, 4} in order , their sum is (18) ,

// Note : duplications are not included when summing , (i.e) the numbers added only once .

// 3- maxTriSum ({-7,12,-7,29,-5,0,-7,0,0,29}) ==> return (41)
// Explanation:
// As the triplet that maximize the sum {12 , 29 , 0} in order , their sum is (41) ,

// Note : duplications are not included when summing , (i.e) the numbers added only once .

function maxTriSum(numbers){
    //remove dupes, sort it decreasingly, take the first three elements, sum it
    return numbers.filter((el, idx, arr) => arr.indexOf(el) === idx).sort((a,b) => b-a).slice(0, 3).reduce((acc, cur) => acc+cur, 0)
}

console.log(maxTriSum([-7,12,-7,29,-5,0,-7,0,0,29])) // 41